 version: '2'
 services:
   nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: jarch-web-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

   jarch-site:
     image: 193862077204.dkr.ecr.us-east-1.amazonaws.com/jarch:site-jarch-static-web
     container_name: jarch-site-static-web
     ports:
       - "8081:8080"
     restart: always
     environment: 
       VIRTUAL_HOST: www.joericearchitect.com
       
