 version: '2'
 services:
   nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: jarch-web-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: jarch-blog
     links:
       - db
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
       VIRTUAL_HOST: blog.joericearchitect.com
       

   jarch-site:
     image: site-jarch-static-web:latest
     container_name: jarch-static-web
     ports:
       - "8081:80"
     restart: always
     environment: 
       VIRTUAL_HOST: www.joericearchitect.com
       
        
