 version: '2'
 services:
   jarch-site:
     image: 193862077204.dkr.ecr.us-east-1.amazonaws.com/jarch:app-mcat-static-web
     container_name: mcat-static-web
     ports:
       - "8081:8080"
     restart: always
     environment: 
       VIRTUAL_HOST: www.minethecatalog.com
       VIRTUAL_PORT: 8081
       
