---
# determine the status of each manager node and break them
# into two groups:
#   - swarm_manager_operational (swarm is running and active)
#   - swarm_manager_bootstrap (host needs to be joined to the cluster)
- hosts: tag_jra_environment_{{ env }}:&tag_jra_swarm_instance_type_swarm_manager
  become: true
  tasks:
    - name: determine swarm status
      shell: >
        docker info | egrep '^Swarm: ' | cut -d ' ' -f2
      register: swarm_status

    - name: create swarm_manager_operational group
      add_host:
        hostname: "{{ item }}"
        groups: swarm_manager_operational
      with_items: "{{ ansible_play_hosts | default(play_hosts) }}"
      when: "'active' in hostvars[item].swarm_status.stdout_lines"
      run_once: true

    - name: create swarm_manager_bootstrap group
      add_host:
        hostname: "{{ item }}"
        groups: swarm_manager_bootstrap
      with_items: "{{ ansible_play_hosts | default(play_hosts) }}"
      when: "'active' not in hostvars[item].swarm_status.stdout_lines"
      run_once: true

# Deploy the www.joericearchitect.com site service
- hosts: swarm_manager_operational[0]
  become: true
  tasks:
    - name: remove jarch-infra-docker-registry service if it exists (ignore failure if it does not exist)
      shell: >
        docker service rm jarch-site-web-static
      ignore_errors: yes

    - name: deploy docker registry service
      shell: >
        docker service create
        --name jarch-site-web-static
        --publish 8080:8080
        --replicas=3
        --network jarch-proxy-traefik-network
        --log-driver=fluentd
        --log-opt fluentd-address=localhost:8282
        --log-opt labels=jra.environment-flip,jra.swarm-node-name,jra.instance-name,jra.environment,jra.environment-size,jra.environment-type,jra.environment-instance-id,jra.failure-zone,jra.subnet-type,jra.swarm-instance-type,jra.swarm-node-type
        --log-opt tag='docker.{{.Name}}'
        --constraint 'node.labels.jra.swarm-node-type == app-ui-web'
        --label traefik.docker.network=jarch-proxy-traefik-network
        --label traefik.port=8080
        --label traefik.frontend.rule=Host:{{ env_domain_prefix }}www.joericearchitect.com
        --label jra.environment-flip=blue
        --label jra.application-name=jarch-site-web-static
        --label jra.container-name=jarch-site-web-static
        --label jra.domain-name={{ env_domain_prefix }}www.joericearchitect.com
        joericearchitect/jarch-site-web-static
